### ISSUE TITLE
Production Ready? 

### ISSUE THREAD

**Issue by NickClark** [gritzko/swarm#64]
A few questions: 

1. Is swarm production ready? 
2. There appears to be no actual production ready Storages (MongoDB, Mysql, Postgres?)
3. How hard is it to make custom a Storage?
3. I don't see a clear strategy for query or collection syncing (Some adds a new item, removes one, etc from a query)

**Comment by gritzko** [comment]
Congratulations, your issue is number 1000000 (binary).
Here are my (likely incomplete) answers:
1. No. Version 0.3 is abandoned due to some difficulties (the math was not good enough to make a production ready system). The upcoming release is very unstable (and backwards incompatible as it uses new awesome math).
2.The upcoming release works on top of LevelUp (practically, leveldb or IndexedDB). It may flush data to whatever other DB, theoretically.
3. If we talk about DB integration (not storage engine) then the answer is "easy". Unfortunately, "easy" integration works one way, i.e. Swarm to some DB (Kafka-like "db as a view" situation).
4. There are various CRDT collection types. 0.3 has Vector and Set. Queries are possible using the aforementioned DB integration (API published queries, not arbitrary queries from the client).

**Comment by NickClark** [comment]
Thank you so much for your prompt and complete-enough answers! :+1:
